name: cooperativa

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: 'Digitality'
      MYSQL_USER: 'cooperativa_user'
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - cooperativa-network

  api-usuarios:
    image: serversideup/php:8.4-fpm-nginx
    volumes:
      - ./APIDeUsuarios:/var/www/html
    ports: 
      - 80:80
    environment:
      SSL_MODE: "off"
